# Change these first
owner: mint-lgbt # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  # Servers
  - name: Ralsei
    check: "tcp-ping"
    url: ralsei.mint.lgbt
    port: 80
    assignees:
      - nixgoat
  - name: Miko
    check: "tcp-ping"
    url: miko.mint.lgbt
    port: 80
    assignees:
      - lunaisnotaboy
  - name: Bunny
    check: "tcp-ping"
    url: bunny.mint.lgbt
    port: 443
    assignees:
      - nixgoat
      
  # Actual services
  - name: Matrix
    url: https://matrix.mint.lgbt:8448/_matrix/federation/v1/version
    icon: https://element.mint.lgbt/vector-icons/apple-touch-icon-72.png
    __dangerous__body_down_if_text_missing: '"server"'
    assignees:
      - nixgoat
  - name: XMPP
    url: https://xmpp.mint.lgbt
    icon: https://xmpp.org/favicon-32x32.png
    assignees:
      - nixgoat
  - name: Femgit
    url: https://fem.mint.lgbt/api/v1/version
    icon: https://fem.mint.lgbt/assets/img/favicon.png
    __dangerous__body_down_if_text_missing: '"version"'
    assignees:
      - lunaisnotaboy
  - name: Chibisafe
    url: https://chibi.mint.lgbt/api/health
    icon: https://chibi.mint.lgbt/apple-touch-icon.png
    __dangerous__body_down_if_text_missing: '"yes"'
    assignees:
      - lunaisnotaboy
  - name: Miniflux
    url: https://rss.mint.lgbt
    icon: https://rss.mint.lgbt/icon/favicon-32.png
    assignees:
      - nixgoat
  - name: CloudTube
    url: https://tube.mint.lgbt
    icon: https://tube.mint.lgbt/static/images/favicon-32x32.png
    assignees:
      - nixgoat
  - name: Redlib
    url: https://redlib.mint.lgbt
    icon: https://redlib.mint.lgbt/touch-icon-iphone.png
    assignees:
      - nixgoat
  - name: 4get
    url: https://search.mint.lgbt/ami4get
    __dangerous__body_down_if_text_missing: '"ok"'
    icon: https://search.mint.lgbt/favicon.ico
    assignees:
      - nixgoat
  - name: Shoelace
    url: https://shoelace.mint.lgbt # i gotta code in a healthcheck for v3 :P
    icon: https://shoelace.mint.lgbt/static/img/shoelace.svg
    assignees:
      - nixgoat
  - name: BreezeWiki
    url: https://breeze.mint.lgbt
    icon: https://breeze.mint.lgbt/static/breezewiki-favicon.svg
    assignees:
      - nixgoat

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mint.lgbt
  # baseUrl: /your-repo-name
  logoUrl: https://mint.lgbt/assets/img/logo.png
  name: mint.lgbt
  introTitle: "Non-profit collective, providing providing services built for and run by LGBTQIA+ people"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: mint.lgbt Status Bot

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
